// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: saynamepb/sayname.proto

package saynamepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SayNameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *SayNameRequest) Reset() {
	*x = SayNameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_saynamepb_sayname_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SayNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayNameRequest) ProtoMessage() {}

func (x *SayNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_saynamepb_sayname_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayNameRequest.ProtoReflect.Descriptor instead.
func (*SayNameRequest) Descriptor() ([]byte, []int) {
	return file_saynamepb_sayname_proto_rawDescGZIP(), []int{0}
}

func (x *SayNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SayNameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GotName string `protobuf:"bytes,1,opt,name=gotName,proto3" json:"gotName,omitempty"`
}

func (x *SayNameResponse) Reset() {
	*x = SayNameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_saynamepb_sayname_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SayNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayNameResponse) ProtoMessage() {}

func (x *SayNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_saynamepb_sayname_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayNameResponse.ProtoReflect.Descriptor instead.
func (*SayNameResponse) Descriptor() ([]byte, []int) {
	return file_saynamepb_sayname_proto_rawDescGZIP(), []int{1}
}

func (x *SayNameResponse) GetGotName() string {
	if x != nil {
		return x.GotName
	}
	return ""
}

var File_saynamepb_sayname_proto protoreflect.FileDescriptor

var file_saynamepb_sayname_proto_rawDesc = []byte{
	0x0a, 0x17, 0x73, 0x61, 0x79, 0x6e, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x2f, 0x73, 0x61, 0x79, 0x6e,
	0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6d, 0x79, 0x67, 0x72, 0x70,
	0x63, 0x22, 0x24, 0x0a, 0x0e, 0x53, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x2b, 0x0a, 0x0f, 0x53, 0x61, 0x79, 0x4e, 0x61,
	0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x6f,
	0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x6f, 0x74,
	0x4e, 0x61, 0x6d, 0x65, 0x32, 0x4c, 0x0a, 0x0e, 0x53, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3a, 0x0a, 0x07, 0x73, 0x61, 0x79, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x16, 0x2e, 0x6d, 0x79, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x61, 0x79, 0x4e, 0x61,
	0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x6d, 0x79, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x53, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x0c, 0x5a, 0x0a, 0x2f, 0x73, 0x61, 0x79, 0x6e, 0x61, 0x6d, 0x65, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_saynamepb_sayname_proto_rawDescOnce sync.Once
	file_saynamepb_sayname_proto_rawDescData = file_saynamepb_sayname_proto_rawDesc
)

func file_saynamepb_sayname_proto_rawDescGZIP() []byte {
	file_saynamepb_sayname_proto_rawDescOnce.Do(func() {
		file_saynamepb_sayname_proto_rawDescData = protoimpl.X.CompressGZIP(file_saynamepb_sayname_proto_rawDescData)
	})
	return file_saynamepb_sayname_proto_rawDescData
}

var file_saynamepb_sayname_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_saynamepb_sayname_proto_goTypes = []interface{}{
	(*SayNameRequest)(nil),  // 0: mygrpc.SayNameRequest
	(*SayNameResponse)(nil), // 1: mygrpc.SayNameResponse
}
var file_saynamepb_sayname_proto_depIdxs = []int32{
	0, // 0: mygrpc.SayNameService.sayName:input_type -> mygrpc.SayNameRequest
	1, // 1: mygrpc.SayNameService.sayName:output_type -> mygrpc.SayNameResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_saynamepb_sayname_proto_init() }
func file_saynamepb_sayname_proto_init() {
	if File_saynamepb_sayname_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_saynamepb_sayname_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SayNameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_saynamepb_sayname_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SayNameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_saynamepb_sayname_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_saynamepb_sayname_proto_goTypes,
		DependencyIndexes: file_saynamepb_sayname_proto_depIdxs,
		MessageInfos:      file_saynamepb_sayname_proto_msgTypes,
	}.Build()
	File_saynamepb_sayname_proto = out.File
	file_saynamepb_sayname_proto_rawDesc = nil
	file_saynamepb_sayname_proto_goTypes = nil
	file_saynamepb_sayname_proto_depIdxs = nil
}
