// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MyServClient is the client API for MyServ service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MyServClient interface {
	SayName(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type myServClient struct {
	cc grpc.ClientConnInterface
}

func NewMyServClient(cc grpc.ClientConnInterface) MyServClient {
	return &myServClient{cc}
}

func (c *myServClient) SayName(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/myServ/sayName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MyServServer is the server API for MyServ service.
// All implementations must embed UnimplementedMyServServer
// for forward compatibility
type MyServServer interface {
	SayName(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedMyServServer()
}

// UnimplementedMyServServer must be embedded to have forward compatible implementations.
type UnimplementedMyServServer struct {
}

func (UnimplementedMyServServer) SayName(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayName not implemented")
}
func (UnimplementedMyServServer) mustEmbedUnimplementedMyServServer() {}

// UnsafeMyServServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MyServServer will
// result in compilation errors.
type UnsafeMyServServer interface {
	mustEmbedUnimplementedMyServServer()
}

func RegisterMyServServer(s grpc.ServiceRegistrar, srv MyServServer) {
	s.RegisterService(&MyServ_ServiceDesc, srv)
}

func _MyServ_SayName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyServServer).SayName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/myServ/sayName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyServServer).SayName(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// MyServ_ServiceDesc is the grpc.ServiceDesc for MyServ service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MyServ_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "myServ",
	HandlerType: (*MyServServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "sayName",
			Handler:    _MyServ_SayName_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "my.proto",
}
